### ISSUE TITLE
Strip original signature from the cslol .dll

### ISSUE THREAD

**Issue by Crauzer** [koobzaar/Exalted#3]
Hi, I'm letting you know on behalf of League Toolkit, that you are distributing our cslol patcher .dll with my own signature. Our license terms clearly state that any other party redistributing it must also re-sign it with their own key. This is to prevent misuse of our tools.

If you want a cheap signing certificate for open-source software, look at this - https://shop.certum.eu/open-source-code-signing.html

**Comment by koobzaar** [comment]
Completely removed the .dll file from the dist and the repo.

**Comment by moonshadow565** [comment]
For anyone reading this, the legal issue here isn't about copyright. It's more of a brand damage kind of situation. Riot Games is known for banning players who use skin-hacking tools, particularly in certain regions like Turkey. Examples of such programs include MKJogo and MKLoL.

What's likely to happen next is that Riot will ban crauzers signature, which means no skin hacks or custom skins. In the best case scenario, they might only block it on certain servers like in the past.

I was really hoping you would have simply opted to re-sign the DLL, as that would have minimized the damage.
By the way, crauzers certificate is set to expire in January 2025, so let's hope it lasts at least until then.

This is all from me.
